# pylint: disable=invalid-name
"""
This is initial py
"""
# Generated by Django 2.1.15 on 2024-03-31 09:13


from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):
    """
    This migration creates the initial schema for the 'lesson' app.
    """
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),#pylint: disable=line-too-long
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), #pylint: disable=line-too-long
            ],
        ),
    ]
