# Generated by Django 4.2.11 on 2024-04-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
