# Generated by Django 4.2.11 on 2024-04-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='bio',
        ),
    ]
