# Generated by Django 4.2.11 on 2024-04-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='add_bio_with_link',
        ),
    ]
