# Generated by Django 4.2.11 on 2024-04-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_description_lesson_add_bio_with_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='add_bio_with_link',
            new_name='description',
        ),
    ]
