# Generated by Django 4.2.11 on 2024-04-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_add_bio_with_link_lesson_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='add_bio_with_link',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
    ]
